### PR TITLE
fix syntax

### PR DESCRIPTION
**Pull request by p-galligan**
removing extra paren

*screaming internally*

### CODE REVIEW

**Comment by helrond** [comment]
@p-galligan wait, version bump too!!!

**Comment by p-galligan** [comment]
Yo, this is weird. I have this branch checked out, and I have the version updated, but is apparently not registering as a change on this commit. Let me try something out.

**Comment by p-galligan** [comment]
I can bump the version up to 0.3.3, but would it just be better to update the 0.3.2 release?

**Comment by helrond** [comment]
I don't think you *can* update that release, since it's pointing at a tag.

**Comment by p-galligan** [comment]
Ah, ok. Well, I'll bump up the version and cut a new release.

**Pull request merged**
